### ISSUE TITLE
Match highlighting is broken when using \n or \r in subject text

### ISSUE THREAD

**Issue by slevithan** [LeaVerou/regexplained#16]
Regexplained has special handling to treat "\r" and "\n" in the subject text as literal line feed and carriage return characters, but this handling is not working correctly.

Simple case (`\n` at start of the match):
Regex: `\n`
Subject text: `\n`
Result: The highlighted match is `n`, rather than `\n`.

With `\n` in middle of the match:
Regex: `a\n`
Subject text: `a\n`
Result: The highlighted match is `a\` (incorrect), rather than `a\n`.

With backreference highlighting:
Regex: `a(\n)`
Subject text: `a\n`
Result: When highlighting the subpattern match, the overall match is shown as `a\` (incorrect) and the subpattern match is shown as `n` (also incorrect, and shown outside of the overall match).

Other curious variations of this issue are possible, depending e.g. on whether `\n` or `\r` appear prior to a match, within a match but prior to a subpattern match, or within a subpattern match.

**Comment by slevithan** [comment]
Closing this since it was fixed by PR #20.

Would it be possible to deploy this change soon? I'm hoping to use regexplained.com with these fixes. 😀

**Comment by LeaVerou** [comment]
It should have been deployed already! Will investigate why it hasn't.

**Comment by LeaVerou** [comment]
Indeed there was an issue. Fixed it and it's deployed now!
