### ISSUE TITLE
Next/prev subpattern highlighting is not always accurate

### ISSUE THREAD

**Issue by slevithan** [LeaVerou/regexplained#7]
Steps to reproduce: Enter `a(a)(a)` as the regex, and `aaa` as the target text. If you click "next subpattern", the first `a` in the text is incorrectly highlighted (it should be the second `a`). Click "next subpattern" again, and the first `a` remains highlighted (it should be the third `a`).

In this case, the problem stems from the fact that the backreference text can be found at multiple positions within the match. But it's possible to trigger the problem even without that, e.g., if a backreference should appear outside or partially outside of the match (thanks to lookahead), but the backreference text is also found within the match.

I know you're aware of this issue (since we previously talked about it), but IMO this is a very significant error for a tool that people will use to help them learn how regexes work.

As you know, JavaScript does not provide any way to accurately determine the starting position of subpattern matches for an arbitrary regex. But here are a couple potential ways to address this:
1. Kill the 'next/previous subpattern' feature. The feature might not be worth saving, if it's inaccurate. Instead, perhaps you could list out the subpattern matches underneath or on the side of the target text.
2.  Use XHR and a programming language on the backend that allows you to determine subpattern match indexes. But then you’d run up against regex syntax and behavior differences between JavaScript and the backend regex flavor.

**Comment by swervo** [comment]
Just came across this myself. I agree with @slevithan in that this is a problem in a tool that is intended to help people learn how regex works (like me).

My test was:
`/<b>|<\/b>/g`

and my string was:
`<b>Bold text</b> <ul><b>​Bold bullet</b></li></ul> <br>`

I really appreciate the effort you have made in producing this tool - unlike some other regex tools it looks really professional which, coupled with the donate button, gives the user a feeling of confidence - unfortunately this seems misplaced at the moment.

**Comment by slevithan** [comment]
This is now fixable using the new regex `/d` (indices) flag from ES2021, which is already supported in Chrome, etc. For regexes that use `/d`, the match result includes start and end positions for all subpattern matches.

**Comment by LeaVerou** [comment]
> This is now fixable using the new regex `/d` (indices) flag from ES2021, which is already supported in Chrome, etc. For regexes that use `/d`, the match result includes start and end positions for all subpattern matches.

Oh that's fantastic!! 
Anyone keen to send a PR? 😁

**Comment by slevithan** [comment]
Will do!

I've been running into a variety of other regexplained bugs while fixing this, though, so expect some additional issue reports (and fixes for them) soon.
